## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset= pd.read_csv("drug200.csv")
dataset

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

## Data - PreProcessing

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [4]:
dataset["Drug"].unique()

array(['DrugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [5]:
dataset["Sex"].unique()

array(['F', 'M'], dtype=object)

In [6]:
dataset["BP"].unique()

array(['HIGH', 'LOW', 'NORMAL'], dtype=object)

In [7]:
dataset["Cholesterol"].unique()

array(['HIGH', 'NORMAL'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
dataset['Drug'] = encoder.fit_transform(dataset['Drug'])
dataset

Age Sex      BP Cholesterol  Na_to_K  Drug
0     23   F    HIGH        HIGH   25.355     0
1     47   M     LOW        HIGH   13.093     3
2     47   M     LOW        HIGH   10.114     3
3     28   F  NORMAL        HIGH    7.798     4
4     61   F     LOW        HIGH   18.043     0
..   ...  ..     ...         ...      ...   ...
195   56   F     LOW        HIGH   11.567     3
196   16   M     LOW        HIGH   12.006     3
197   52   M  NORMAL        HIGH    9.894     4
198   23   M  NORMAL      NORMAL   14.020     4
199   40   F     LOW      NORMAL   11.349     4

[200 rows x 6 columns]

In [9]:
dataset["Drug"].unique()

array([0, 3, 4, 1, 2])

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    int32  
dtypes: float64(1), int32(1), int64(1), object(3)
memory usage: 8.7+ KB


In [11]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
dataset['Sex'] = encoder.fit_transform(dataset['Sex'])
dataset["BP"]= encoder.fit_transform(dataset["BP"])
dataset["Cholesterol"]= encoder.fit_transform(dataset["Cholesterol"])
dataset

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    0   0            0   25.355     0
1     47    1   1            0   13.093     3
2     47    1   1            0   10.114     3
3     28    0   2            0    7.798     4
4     61    0   1            0   18.043     0
..   ...  ...  ..          ...      ...   ...
195   56    0   1            0   11.567     3
196   16    1   1            0   12.006     3
197   52    1   2            0    9.894     4
198   23    1   2            1   14.020     4
199   40    0   1            1   11.349     4

[200 rows x 6 columns]

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    int32  
 2   BP           200 non-null    int32  
 3   Cholesterol  200 non-null    int32  
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    int32  
dtypes: float64(1), int32(4), int64(1)
memory usage: 6.4 KB


## Training and Test Set

In [13]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

## Splitting the dataset into Training and Test Set

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)


## Features Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [21]:
y_pred = classifier.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print("Y_test versus y_pred\n\n")
print(cm)
accuracy_score(y_test,y_pred)

Y_test versus y_pred


[[13  0  2  0  1]
 [ 0  5  0  0  0]
 [ 0  1  5  0  0]
 [ 0  0  0  2  0]
 [ 0  0  0  0 11]]


0.9